;; -*- mode: eask; lexical-binding: t -*-

(package "gptel-prompts"
         "1.0.0"
         "Manage gptel-directives in individual files")

(website-url "https://github.com/jwiegley/gptel-prompts")
(keywords "gptel" "prompts" "directives")

(package-file "gptel-prompts.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.1")
